### ISSUE TITLE
Создать и описать класс события

### ISSUE THREAD

**Issue by mefest** [UjGamer/shusai#1]
Создать и описать класс события

описать основные поля и методы, далее будет уточняться

**Comment by mefest** [comment]
сделай по примеру как описанно в коментарии
https://github.com/UjGamer/shusai/issues/3#issuecomment-292789868

**Comment by UjGamer** [comment]
@mefest у Event интерфейс будет посложнее, прототип сейчас набросаю по-быстрому

**Comment by UjGamer** [comment]
Merged PR from @inagen - 2d9810aff1c1188cd0a6ec0b2be439f2dae281e1
